upstreams:
  - name: user_service
    instances:
      - http://user_service_1:8001
      - http://user_service_2:8002

  - name: order_service
    instances:
      - http://order_service_1:8003
      - http://order_service_2:8004

  - name: product_service
    instances:
      - http://product_service_1:8005
      - http://product_service_2:8006

circuit_breaker:
  failure_threshold: 5
  recovery_timeout: 60s
  half_open_requests: 2

routes:
  - path: /docs
    methods: ["get"]
    auth_required: false
    limit_requests: false
    revoke_token: false
    roles: [admin, user]

  - path: /relay/openapi.json
    methods: ["get"]
    auth_required: false
    limit_requests: false
    revoke_token: false
    roles: [admin, user]

  - path: /api/v1/auth
    methods: ["get", "post", "patch", "delete"]
    strip_prefix: /api/v1
    auth_required: false
    limit_requests: true
    revoke_token: false
    roles: [admin, user]
    rate_limit:
      requests: 10
      window: 120s
      key_by: ip
    exceptions:
      - path: "/api/v1/auth/me"
        method: get
        auth_required: true
        rate_limit:
          requests: 10
          window: 120s
          key_by: user_email

      - path: "/api/v1/auth/refresh"
        method: post
        revoke_token: true
        rate_limit:
          requests: 10
          window: 120s
          key_by: ip

      - path: "/api/v1/auth/logout"
        method: post
        auth_required: true
        revoke_token: true
        rate_limit:
          requests: 10
          window: 120s
          key_by: user_email

      - path: "/api/v1/auth"
        method: delete
        auth_required: true
        revoke_token: true
        rate_limit:
          requests: 10
          window: 120s
          key_by: user_email

  - path: /api/v1/products
    methods: ["get", "post", "patch", "delete"]
    strip_prefix: /api/v1
    auth_required: true
    limit_requests: true
    revoke_token: false
    roles: [admin, user]
    rate_limit:
      requests: 50
      window: 60s
      key_by: user_email
    exceptions:
      - path: "/api/v1/products"
        method: post
        roles: [admin]
        rate_limit:
          requests: 50
          window: 60s
          key_by: user_email

      - path: "/api/v1/products/{id}"
        method: patch
        roles: [admin]
        rate_limit:
          requests: 50
          window: 60s
          key_by: user_email

      - path: "/api/v1/products/{id}"
        method: delete
        roles: [admin]
        rate_limit:
          requests: 50
          window: 60s
          key_by: user_email

  - path: /api/v1/orders
    methods: ["get", "post", "delete"]
    strip_prefix: /api/v1
    auth_required: true
    limit_requests: true
    revoke_token: false
    roles: [admin, user]
    rate_limit:
      requests: 50
      window: 60s
      key_by: user_email

  - path: /api/v1/carts
    methods: ["get", "post", "patch", "delete"]
    strip_prefix: /api/v1
    auth_required: true
    limit_requests: true
    revoke_token: false
    roles: [admin, user]
    rate_limit:
      requests: 50
      window: 60s
      key_by: user_email

  - path: /api/v1/admin
    methods: ["patch"]
    strip_prefix: /api/v1
    auth_required: true
    limit_requests: true
    revoke_token: false
    roles: [admin]
    rate_limit:
      requests: 10
      window: 120s
      key_by: user_email
