"""add proxy to upstream enum and change latency_ms type to string

Revision ID: 2da6da0774e0
Revises: 8031b998327f
Create Date: 2026-08-14 11:31:30.007134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2da6da0774e0'
down_revision: Union[str, Sequence[str], None] = '8031b998327f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE upstreamtype ADD VALUE 'proxy'")
    op.alter_column('logs', 'latency_ms',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'latency_ms',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
