"""add logs table

Revision ID: 8031b998327f
Revises: 8c3c0683190d
Create Date: 2026-08-12 17:18:42.728619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8031b998327f'
down_revision: Union[str, Sequence[str], None] = '8c3c0683190d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('span_id', sa.UUID(), nullable=False),
    sa.Column('parent_span_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('client_ip', postgresql.INET(), nullable=True),
    sa.Column('upstream', sa.Enum('relay', 'user_service', 'order_service', 'product_service', name='upstreamtype'), nullable=False),
    sa.Column('upstream_instance', sa.String(), nullable=True),
    sa.Column('upstream_url', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('log_level', sa.Enum('info', 'debug', 'error', name='loglevel'), nullable=False),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('circuit_open', sa.Boolean(), nullable=True),
    sa.Column('rate_limited', sa.Boolean(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='logs_user_id_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='logs_pk'),
    sa.UniqueConstraint('trace_id', 'span_id', 'parent_span_id', name='logs_unique_key')
    )
    op.create_index('idx_logs_trace_span', 'logs', ['trace_id', 'span_id'], unique=False)
    op.create_index('idx_logs_trace_upstream', 'logs', ['trace_id', 'upstream'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_logs_trace_upstream', table_name='logs')
    op.drop_index('idx_logs_trace_span', table_name='logs')
    op.drop_table('logs')
    # ### end Alembic commands ###
