"""remove carts and cart_items tables

Revision ID: add8f7013b4d
Revises: e2aa42355e8f
Create Date: 2026-08-19 01:36:48.009115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'add8f7013b4d'
down_revision: Union[str, Sequence[str], None] = 'e2aa42355e8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_cart_items_created_at'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('idx_cart_created_at'), table_name='carts')
    op.drop_index(op.f('idx_cart_user_id_comp'), table_name='carts')
    op.drop_table('carts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('items', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('cart_user_id_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('carts_pk'))
    )
    op.create_index(op.f('idx_cart_user_id_comp'), 'carts', ['id', 'user_id'], unique=False)
    op.create_index(op.f('idx_cart_created_at'), 'carts', ['created_at'], unique=False)
    op.create_table('cart_items',
    sa.Column('cart_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=4, scale=0), autoincrement=False, nullable=False),
    sa.Column('total_price', sa.NUMERIC(precision=4, scale=0), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], name=op.f('cart_items_cart_id_fk'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('cart_items_product_id_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cart_id', 'product_id', name=op.f('cart_items_pk'))
    )
    op.create_index(op.f('idx_cart_items_created_at'), 'cart_items', ['created_at'], unique=False)
    # ### end Alembic commands ###
