"""add not null constraint to product_reserves pks

Revision ID: e24cbf4df7ca
Revises: add8f7013b4d
Create Date: 2026-08-20 16:47:27.482136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e24cbf4df7ca'
down_revision: Union[str, Sequence[str], None] = 'add8f7013b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
