"""add task_id column to logs table

Revision ID: e2aa42355e8f
Revises: 2da6da0774e0
Create Date: 2026-08-15 14:46:20.036845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2aa42355e8f'
down_revision: Union[str, Sequence[str], None] = '2da6da0774e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('task_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'task_id')
    # ### end Alembic commands ###
